---
- name: Install and Configure Samba
  hosts: smb
  become: true

  tasks:
    - name: Install Samba
      ansible.builtin.apt:
        name: samba
        state: present

    - name: Create public share directory
      ansible.builtin.file:
        path: /srv/samba/public
        state: directory
        owner: nobody
        group: nogroup
        mode: "0755"

    - name: Configure smb.conf for backward compatibility
      ansible.builtin.template:
        src: templates/smb.conf.j2
        dest: /etc/samba/smb.conf
        mode: "0644"
        backup: true
      notify: Restart samba

    - name: Enable Samba services on boot
      ansible.builtin.service:
        name: smbd
        enabled: true

  handlers:
    - name: Restart samba
      ansible.builtin.service:
        name: smbd
        state: restarted
