---
- name: Install and configure Nginx for smb.hostomega.com
  hosts: smb
  become: true
  tasks:
    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true

    - name: Install Certbot and Nginx plugin
      ansible.builtin.apt:
        name:
          - certbot
          - python3-certbot-nginx
        state: present
        update_cache: true

    - name: Create Nginx configuration file for smb.hostomega.com
      ansible.builtin.copy:
        dest: /etc/nginx/sites-available/smb.hostomega.com
        content: |
          server {
              listen 80;
              server_name smb.hostomega.com;

              location /Public {
                  alias /srv/samba/public;
                  autoindex on;                # Enable directory listing
                  autoindex_exact_size off;    # Show human-readable file sizes
                  autoindex_localtime on;      # Show file timestamps in local time
              }

              # Optional: Error logs for troubleshooting
              error_log /var/log/nginx/smb-1.error.log;
              access_log /var/log/nginx/smb-1.access.log;

              location / {
                  return 302 http://$host/Public/;
              }
          }
        owner: root
        group: root
        mode: "0644"

    - name: Enable smb.hostomega.com site
      ansible.builtin.file:
        src: /etc/nginx/sites-available/smb.hostomega.com
        dest: /etc/nginx/sites-enabled/smb.hostomega.com
        state: link

    - name: Test Nginx configuration
      ansible.builtin.command:
        cmd: nginx -t
      register: nginx_test_result
      failed_when: nginx_test_result.rc != 0
      changed_when: false

    - name: Reload Nginx to apply changes
      ansible.builtin.systemd:
        name: nginx
        state: reloaded

    - name: Obtain SSL certificate with Certbot
      ansible.builtin.command:
        cmd: certbot --nginx -d smb.hostomega.com --non-interactive --agree-tos --email optical.mahir@gmail.com
      register: certbot_result
      changed_when: "'Certbot' in certbot_result.stdout"

    - name: Ensure Certbot auto-renewal cron job is set up
      ansible.builtin.cron:
        name: "Certbot Auto Renewal"
        special_time: monthly
        job: "/usr/bin/certbot renew --quiet && systemctl reload nginx"
        user: root
        state: present
      changed_when: false
